version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    command: /app/entrypoint.sh
    volumes:
      - nfsvolume:/app

volumes:
  nfsvolume:
    driver_opts:
      type: "nfs"
      o: "addr=192.168.1.107,nolock,soft,rw"
      device: ":/mnt/nfsshare"
    # depends_on:
    #   - db
  # db:
  #   image: postgres:13
  #   restart: always
  #   environment:
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_USER: postgres
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - pg_data:/var/lib/postgresql/data  # Define a volume for the database data


# volumes:
#   pg_data:  # Define a named volume for database data persistence