# Generated by Django 4.2.6 on 2023-10-24 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercise_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='exercise',
            name='updated_at',
        ),
    ]
